POST http://localhost:8080/save HTTP/1.1
content-Type: application/json

{
    "name": "Alejandra",
    "apellido" : "apellido",
    "identificacion": "212",
    "correp" : "manu@gmail.com",
    "contrasena" : "contrasena",
    "rol" : "rol",
    "estado" : "estado"
}   

### 
GET http://localhost:8080 HTTP/1.1
content-Type: application/json

### 
Post http://localhost:8080/update/746 HTTP/1.1
content-Type: application/json

{
    "nombre": "Alejandra",
    "identificacion": "13342443"
}

### 

GET http://localhost:8080/find/198 HTTP/1.1
content-Type: application/json

### 

GET http://localhost:8080/delete/618 HTTP/1.1
content-Type: application/json